# Generated by Django 3.0.3 on 2020-02-12 03:51

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('mat_aluno', models.AutoField(primary_key=True, serialize=False, verbose_name='Matricula Aluno')),
                ('nome_aluno', models.CharField(max_length=50, verbose_name='Nome Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador Curso')),
                ('nome_curso', models.CharField(max_length=50, verbose_name='Nome do Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False, verbose_name='Matricula Professor')),
                ('nome_professor', models.CharField(max_length=50, verbose_name='Nome Professor')),
                ('matricula_professor', models.CharField(max_length=50, verbose_name='Matricula Professor')),
                ('condicao_professor', models.CharField(choices=[('INTERNO', 'INTERNO'), ('EXTERNO', 'EXTERNO')], default='INTERNO', max_length=50, verbose_name='Externo ou Interno')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('nome_sala', models.CharField(max_length=50, verbose_name='Nome Sala')),
                ('localizacao_sala', models.CharField(max_length=50, verbose_name='Localização da Sala')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('nome_turma', models.CharField(max_length=50, verbose_name='Nome da Turma')),
                ('periodo_turma', models.IntegerField(verbose_name='Periodo Turma')),
                ('id_curso_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Curso', to='core.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Tcc',
            fields=[
                ('id_tcc', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador TCC')),
                ('ano_tcc', models.IntegerField(verbose_name='Ano')),
                ('tema_tcc', models.CharField(max_length=100, verbose_name='Tema TCC')),
                ('carta_aceite_tcc', models.FileField(blank=True, null=True, upload_to=core.models.tcc_directory_path, verbose_name='CartadeAceita')),
                ('convite_banca_tcc', models.FileField(blank=True, null=True, upload_to=core.models.tcc_directory_path, verbose_name='ConviteBanca')),
                ('marcacao_banca_tcc', models.FileField(blank=True, null=True, upload_to=core.models.tcc_directory_path, verbose_name='MarcaçãoBanca')),
                ('banca1_tcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bancaexaminadora', to='core.Professor')),
                ('banca2_tcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bancae_xaminadora', to='core.Professor')),
                ('co_orientador_tcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Coorientador', to='core.Professor')),
                ('id_aluno_tcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AutorTcc', to='core.Aluno')),
                ('id_curso_tcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NomeCurso', to='core.Curso')),
                ('orientador_tcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orientador', to='core.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id_coordenador', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador Coornedaor')),
                ('nome_coordenador', models.CharField(max_length=50, verbose_name='Nome Coordenador')),
                ('id_curso_coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso', verbose_name='Curso')),
            ],
        ),
        migrations.CreateModel(
            name='AppTcc',
            fields=[
                ('id_apptcc', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador Apresentacao')),
                ('dt_apptcc', models.DateTimeField(verbose_name='Data e Hora da Apresentacao')),
                ('id_sala_apptcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SaladaApresentacao', to='core.Sala')),
                ('id_tcc_apptcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TemaApresentacao', to='core.Tcc')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='id_curso_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso', verbose_name='Curso'),
        ),
    ]
