# Generated by Django 3.0.3 on 2020-02-14 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defesa',
            fields=[
                ('id_df', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador Apresentacao')),
                ('dt_df', models.DateTimeField(verbose_name='Data e Hora da Apresentacao')),
            ],
            options={
                'verbose_name': 'Defesa',
                'verbose_name_plural': 'Defesas',
            },
        ),
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='coordenador',
            options={'verbose_name': 'Coordenador', 'verbose_name_plural': 'Coordenadores'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AlterModelOptions(
            name='tcc',
            options={'verbose_name': 'Tcc', 'verbose_name_plural': 'Tccs'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.RemoveField(
            model_name='tcc',
            name='banca1_tcc',
        ),
        migrations.RemoveField(
            model_name='tcc',
            name='banca2_tcc',
        ),
        migrations.DeleteModel(
            name='AppTcc',
        ),
        migrations.AddField(
            model_name='defesa',
            name='banca1_df',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bancaexaminadora_defesa', to='core.Professor'),
        ),
        migrations.AddField(
            model_name='defesa',
            name='banca2_df',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bancae_xaminadora_defesa', to='core.Professor'),
        ),
        migrations.AddField(
            model_name='defesa',
            name='id_sala_df',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SaladaApresentacao', to='core.Sala'),
        ),
        migrations.AddField(
            model_name='defesa',
            name='id_tcc_df',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TemaApresentacao', to='core.Tcc'),
        ),
    ]
