# Generated by Django 3.0.3 on 2020-02-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200215_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='periodo_turma',
            field=models.CharField(max_length=6, verbose_name='Periodo Turma'),
        ),
    ]
