# Generated by Django 3.0.3 on 2020-02-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200215_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcc',
            name='ano_tcc',
        ),
        migrations.AddField(
            model_name='tcc',
            name='id_turma_tcc',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='id_turma_tcc', to='core.Turma'),
            preserve_default=False,
        ),
    ]
