# Generated by Django 3.0.3 on 2020-02-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200215_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='status_turma',
            field=models.CharField(blank=True, choices=[('ATIVO', 'ATIVO'), ('ENCERRADA', 'ENCERRADA')], default='ATIVO', max_length=50, null=True, verbose_name='Em Andamento ou Encerrada'),
        ),
    ]
