# Generated by Django 3.0.3 on 2020-02-16 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_turma_status_turma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcc',
            options={'verbose_name': 'tcc', 'verbose_name_plural': 'tccs'},
        ),
        migrations.AlterField(
            model_name='defesa',
            name='id_tcc_df',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_tcc_df', to='core.tcc'),
        ),
    ]
