# Generated by Django 3.0.3 on 2020-02-16 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200215_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcc',
            name='status_tcc',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Analise', 'Em Analise'), ('Resolvido', 'Resolvido')], default='Pendente', max_length=50),
        ),
        migrations.AlterField(
            model_name='defesa',
            name='id_tcc_df',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_tcc_df', to='core.tcc'),
        ),
    ]
