# Generated by Django 3.0.2 on 2020-02-16 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200216_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name': 'turma', 'verbose_name_plural': 'turmas'},
        ),
        migrations.AddField(
            model_name='aluno',
            name='periodo_aluno',
            field=models.CharField(default='2020.1', max_length=6, verbose_name='Periodo Turma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defesa',
            name='id_tcc_df',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_tcc_df', to='core.tcc'),
        ),
    ]
