# Generated by Django 3.0.3 on 2020-02-29 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200216_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador Periodo')),
                ('nome_periodo', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': '2.Periodo',
                'verbose_name_plural': '2.Periodos',
            },
        ),
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': '7.Aluno', 'verbose_name_plural': '7.Alunos'},
        ),
        migrations.AlterModelOptions(
            name='coordenador',
            options={'verbose_name': '3.Coordenador', 'verbose_name_plural': '3.Coordenadores'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': '1.Curso', 'verbose_name_plural': '1.Cursos'},
        ),
        migrations.AlterModelOptions(
            name='defesa',
            options={'verbose_name': '9.Defesa', 'verbose_name_plural': '9.Defesas'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': '4.Professor', 'verbose_name_plural': '4.Professores'},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'verbose_name': '6.Sala', 'verbose_name_plural': '6.Salas'},
        ),
        migrations.AlterModelOptions(
            name='tcc',
            options={'verbose_name': '8.Tcc', 'verbose_name_plural': '8.Tccs'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name': '5.Turma', 'verbose_name_plural': '5.Turmas'},
        ),
        migrations.AlterField(
            model_name='defesa',
            name='id_tcc_df',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_tcc_df', to='core.tcc'),
        ),
    ]
