# Generated by Django 3.0.3 on 2020-02-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200229_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenador',
            name='dt_final',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final'),
        ),
        migrations.AlterField(
            model_name='defesa',
            name='id_tcc_df',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_tcc_df', to='core.tcc'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='dt_final',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final'),
        ),
    ]
