# Generated by Django 3.0.3 on 2020-03-01 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200229_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='matricula_aluno',
            field=models.CharField(default='9999', max_length=15, verbose_name='Matricula Aluno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tcc',
            name='professor_disciplica_tcc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='professor_disciplica_tcc', to='core.Professor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defesa',
            name='id_tcc_df',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_tcc_df', to='core.tcc'),
        ),
    ]
