# Generated by Django 3.0.3 on 2020-03-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200301_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defesa',
            name='id_tcc_df',
        ),
    ]
