# Generated by Django 3.0.3 on 2020-03-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_defesa_id_tcc_df'),
    ]

    operations = [
        migrations.AddField(
            model_name='defesa',
            name='id_tcc_df',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_tcc_df', to='core.tcc'),
            preserve_default=False,
        ),
    ]
