# Generated by Django 3.0.3 on 2020-03-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200301_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defesa',
            name='id_tcc_df',
        ),
        migrations.AddField(
            model_name='defesa',
            name='id_tcc_df_df',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_tcc_df_df', to='core.tcc'),
            preserve_default=False,
        ),
    ]
