# Generated by Django 3.0.3 on 2020-03-01 14:12

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200301_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dfe',
            name='id_tcc_dfe',
        ),
        migrations.AlterField(
            model_name='periodo',
            name='id_tcc_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_tcc_periodo', to='core.tcc'),
        ),
        migrations.CreateModel(
            name='TccAjuste',
            fields=[
                ('id_tc', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador TCC')),
                ('titulo_tc', models.CharField(max_length=100, verbose_name='Titulo TCC')),
                ('carta_aceite_tc', models.FileField(blank=True, null=True, upload_to=core.models.tcc_directory_path, verbose_name='CartadeAceita')),
                ('convite_banca_tc', models.FileField(blank=True, null=True, upload_to=core.models.tcc_directory_path, verbose_name='ConviteBanca')),
                ('marcacao_banca_tc', models.FileField(blank=True, null=True, upload_to=core.models.tcc_directory_path, verbose_name='MarcaçãoBanca')),
                ('status_tc', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Analise', 'Em Analise'), ('Resolvido', 'Resolvido')], default='Pendente', max_length=50)),
                ('co_orientador_tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_orientador_tc', to='core.Professor')),
                ('id_aluno_tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_aluno_tc', to='core.Aluno')),
                ('id_curso_tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_curso_tc', to='core.Curso')),
                ('id_turma_tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turma')),
                ('orientador_tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientador_tc', to='core.Professor')),
                ('professor_disciplica_tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_disciplica_tc', to='core.Professor')),
            ],
        ),
    ]
