# Generated by Django 3.0.3 on 2020-03-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200301_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='id_tcc_periodo',
        ),
    ]
