# Generated by Django 3.0.3 on 2020-03-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_periodo_id_tcc_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tccajuste',
            name='professor_disciplica_tc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_disciplica_tc', to='core.Professor'),
        ),
    ]
