# Generated by Django 3.0.3 on 2020-03-01 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_dfe_id_tccajuste_dfe'),
    ]

    operations = [
        migrations.AddField(
            model_name='defesa',
            name='id_tccajuste_df',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_tccajuste_df', to='core.TccAjuste'),
        ),
    ]
