# Generated by Django 3.0.3 on 2020-03-01 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_defesa_id_tccajuste_df'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tccajuste',
            name='co_orientador_tc',
        ),
        migrations.RemoveField(
            model_name='tccajuste',
            name='id_aluno_tc',
        ),
        migrations.RemoveField(
            model_name='tccajuste',
            name='id_curso_tc',
        ),
        migrations.RemoveField(
            model_name='tccajuste',
            name='id_turma_tc',
        ),
        migrations.RemoveField(
            model_name='tccajuste',
            name='orientador_tc',
        ),
        migrations.RemoveField(
            model_name='tccajuste',
            name='professor_disciplica_tc',
        ),
        migrations.AlterField(
            model_name='defesa',
            name='id_tccajuste_df',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_tcc_df', to='core.tcc'),
        ),
        migrations.DeleteModel(
            name='dfe',
        ),
        migrations.DeleteModel(
            name='TccAjuste',
        ),
    ]
