# Generated by Django 3.0.3 on 2020-03-01 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200301_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defesa',
            name='id_tccajuste_df',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_tcc_df', to='core.tcc'),
        ),
    ]
