# Generated by Django 3.0.3 on 2020-03-01 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20200301_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defesa',
            name='id_tcc_df',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_tcc_df', to='core.tcc'),
        ),
        migrations.AlterField(
            model_name='tcc',
            name='id_tcc',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tcc',
            name='status_tcc',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em_Analise', 'Em_Analise'), ('Resolvido', 'Resolvido')], default='Pendente', max_length=50),
        ),
    ]
