# Generated by Django 3.0.3 on 2020-03-01 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20200301_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defesa',
            name='id_tcc_df',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_tcc_df', to='core.tcc'),
        ),
    ]
