# Generated by Django 3.0.3 on 2020-03-01 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20200301_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcc',
            name='entrega_cd_tcc',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=50),
        ),
        migrations.AlterField(
            model_name='defesa',
            name='id_teste',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.tcc'),
        ),
        migrations.AlterField(
            model_name='tcc',
            name='status_tcc',
            field=models.CharField(choices=[('Em Curso', 'Em Curso'), ('abandono', 'abandono'), ('reprovado', 'reprovado'), ('aprovado', 'aprovado')], default='Em Curso', max_length=50),
        ),
    ]
